export const TILE_SIZE = 16;
export const PLAYER_SPEED = 90; // pixels per second
export const INTERACTION_RANGE = 32; // pixels
export const VIEWPORT_WIDTH = 800;
export const VIEWPORT_HEIGHT = 480;
export const MAX_CANVAS_WIDTH = 1024;
export const CLICK_ARRIVE_THRESHOLD = 4; // pixels — close enough to count as "arrived"
export const MIN_ZOOM = 2.0;
export const MAX_ZOOM = 4.0;
export const DEFAULT_ZOOM = 3.0;
export const ZOOM_STEP = 0.1;
