export const TILE_SIZE = 32;
export const PLAYER_SPEED = 180; // pixels per second
export const INTERACTION_RANGE = 64; // pixels
export const VIEWPORT_WIDTH = 640;
export const VIEWPORT_HEIGHT = 480;
export const MAX_CANVAS_WIDTH = 1024;
export const CLICK_ARRIVE_THRESHOLD = 4; // pixels — close enough to count as "arrived"
export const MIN_ZOOM = 0.6;
export const MAX_ZOOM = 1.2 ;
export const DEFAULT_ZOOM = 1.0;
export const ZOOM_STEP = 0.1;
