import { promises as fs } from 'fs';
import path from 'path';

const ME_ROOT = path.join(process.cwd(), 'public', 'assets', 'me');

/** Whitelist theme folder names — they're auto-generated by the pack and
 * follow `<digits>_<words>_Singles_16x16`. Reject anything else so we can't
 * be tricked into reading outside the pack root. */
function sanitizeTheme(name: string): string | null {
  return /^[0-9A-Za-z_]+_Singles_16x16$/.test(name) ? name : null;
}

/** List PNG filenames inside a single theme folder. Returns names without the
 * `.png` extension, which the editor turns into pack-tile keys of shape
 * `me:<theme>/<stem>`. */
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ name: string }> },
): Promise<Response> {
  const { name: rawName } = await params;
  const name = sanitizeTheme(rawName);
  if (!name) return Response.json({ error: 'Invalid theme name' }, { status: 400 });

  try {
    const dir = path.join(ME_ROOT, name);
    const entries = await fs.readdir(dir);
    const files = entries
      .filter(f => f.toLowerCase().endsWith('.png'))
      .map(f => f.slice(0, -'.png'.length))
      .sort();
    return Response.json({ files });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return Response.json({ error: 'Theme not found' }, { status: 404 });
    }
    return Response.json({ error: String(err) }, { status: 500 });
  }
}
